---
- name: Set fact for operation 
  set_fact:
    service_operation: "{{ next_state['status'] }}"
  loop: "{{ gtm_pool_state_list }}"
  loop_control:
    loop_var: next_state
  when:
   - operation is defined
   - next_state.operation == operation

- name: Change of GSLB pool member using REST
  uri: 
    url: https://{{ ansible_host }}//mgmt/tm/gtm/pool/a/{{ item['poolName']['description'] | replace('/','~') }}/members/{{ item['serverName']['description'] | replace('/','~') }}:{{ item['vsName']['description'] | replace('/','~')  }} 
    method: PATCH
    validate_certs: false
    headers:
       X-F5-Auth-Token: "{{ bigip_auth_token }}" 
    body:
      "{{ service_operation }}"
    body_format: json
  delegate_to: localhost
  register: rest
  when: 
   - operation is defined
   - datacentre | upper in item['vsName']['description'] | upper
  loop: "{{ parsed_gtm_pool_stats }}"

- name: Gather post-change GSLB pool data 
  set_fact:
    parsed_post_gtm_pool_stats: "{{ parsed_gtm_pool_stats + [item['value']['nestedStats']['entries']] }}"
  loop: "{{ output_stats['json']['entries'] | dict2items }}"
  when: parsed_post_gtm_pool_stats is defined

#- name: Ensure data status 