---
# tasks file for f5_gslb_manager
- name: Retrieve gtm pool members 
  uri: 
    url: https://{{ ansible_host }}/mgmt/tm/gtm/pool/a/~{{ partition }}~{{ gslb_pool_name }}/members
    method: GET
    validate_certs: false
    headers:
       X-F5-Auth-Token: "{{ bigip_auth_token }}" 
    body:
  delegate_to: localhosts
  register: output

- name: Retrieve availability status of GTM pool members
  uri: 
    url: https://{{ ansible_host }}/mgmt/tm/gtm/pool/a/~{{ partition }}~{{ gslb_pool_name }}/members/stats
    method: GET
    validate_certs: false
    headers:
       X-F5-Auth-Token: "{{ bigip_auth_token }}" 
    body:
  delegate_to: localhosts
  register: output_stats

- name: Gather GSLB members 
  set_fact:
    parsed_gtm_pool: "{{ parsed_gtm_pool + [item] }}"
  loop: "{{ output['json']['items'] }}"
  when: parsed_post_gtm_pool_stats is undefined

- name: Gather pre-change GSLB pool data
  set_fact:
    parsed_gtm_pool_stats: "{{ parsed_gtm_pool_stats + [item['value']['nestedStats']['entries']] }}"
  loop: "{{ output_stats['json']['entries'] | dict2items }}"
  when: parsed_post_gtm_pool_stats is undefined

- name: Change the state of pool members.
  include_tasks: change_pool_state.yml
