- name: Create Virtual Server
  connection: local
  gather_facts: false
  hosts: dev_f5
  tasks:
    - name: Login to F5 IControl REST
      include_role:
        name: f5_rest_login

    - name: Create Nodes
      include_tasks:
        file: './tasks/create_nodes.yml'
      vars:ยง
        nodes: "{{ ltm_resource_def.ltm_nodes }}"
  
    - name: Create SNAT Pools
      include_tasks:
        file: './tasks/create_snatpools.yml'
      vars:
        snat: "{{ item }}"
      loop:  "{{ ltm_resource_def.snat_pools }}"

    - name: Create LTM Pools
      include_tasks:
        file: './tasks/create_ltm_pools.yml'
      vars:
        pool: "{{ next_ltm_pool }}"
      loop:  "{{ ltm_resource_def.ltm_pools }}"
      loop_control:
        loop_var: next_ltm_pool

    - name: Create LTM Virtual Server
      include_tasks:
        file: './tasks/create_ltm_virtual.yml'
      vars:
        virtual: "{{ item }}"
      loop:  "{{ ltm_resource_def.virtuals }}"