---
- name: Retrieve F5 Data
  connection: local
  gather_facts: false
  hosts: dev_f5
  
  tasks:
    - name: Login to F5 IControl REST
      include_role:
        name: f5_rest_login

    - name: Get All F5 data 
      uri: 
        url: https://{{ ansible_host }}/mgmt/tm/ltm/{{item }}
        method: GET
        validate_certs: false
        headers:
           X-F5-Auth-Token: "{{ bigip_auth_token }}"
      delegate_to: localhost
      register: data
      loop:
      - node
      - snatpool
      - snat-translation
      - pool
      - virtual
      loop_control:
        pause: 2

    - name: Save F5 data to file
      copy:
        content: "{{ data['results'] | to_nice_json }}"
        dest: "./files/{{ inventory_hostname }}-f5-data.json"
      delegate_to: localhost